#IMPORTANT NOTICE:
#You can add more entries using KubeJS
#https://github.com/tom5454/Create-Ore-Excavation#kubejs
importantInfo = true
#Weight value for empty chunk
#Range: > 1
generationChance = 5000
#Finite vein base amount
#Range: > 1
finiteAmountBase = 10000
#Veins infinite by default
defaultInfinite = false
#Max number of extractor per ore vein, Set to 0 for infinite
#Range: 0 ~ 64
maxExtractorsPerVein = 0

