
#ElementalCraft config
[elementalcraft]

	#Instruments config
	[elementalcraft.instruments]

		[elementalcraft.instruments.tank]
			#The element capacity of a small element container.
			#Range: 0 ~ 100000000
			tankSmallCapacity = 1000
			#The element capacity of a element container.
			#Range: 0 ~ 100000000
			tankCapacity = 100000
			#The element capacity of a element reservoir.
			#Range: 0 ~ 100000000
			reservoirCapacity = 5000000

		[elementalcraft.instruments.extractor]
			#The amount of element extracted by an extractor.
			#Range: 0 ~ 100
			extractorExtractionAmount = 5
			#The max amount ofrunes on an extractor.
			#Range: 0 ~ 10
			extractorMaxRunes = 1
			#The amount of element extracted by an improved extractor.
			#Range: 0 ~ 500
			improvedExtractorExtractionAmount = 25
			#The max amount of runes on an improved extracto.
			#Range: 0 ~ 10
			improvedExtractoMaxRunes = 3

		[elementalcraft.instruments.evaporator]
			#The amount of element extracted by an evaporator.
			#Range: 0 ~ 100
			evaporatorExtractionAmount = 1
			#The max amount of runes on an evaporator.
			#Range: 0 ~ 10
			evaporatorMaxRunes = 1

		[elementalcraft.instruments.solarSythesizer]
			#The max amount of runes on a Solar Sythesizer.
			#Range: 0 ~ 10
			solarSythesizerMaxRunes = 2
			#the multiplier of lense in the Solar Sythesizer (based on 1500)
			#Range: 0 ~ 100
			solarSythesizerLenseElementMultiplier = 10

		[elementalcraft.instruments.diffuser]
			#The amount of element transfered by a diffuser.
			#Range: 0 ~ 100
			diffuserDiffusionAmount = 5
			#The max amount of runes on a diffuser.
			#Range: 0 ~ 10
			diffuserMaxRunes = 3
			#The range of a diffuser.
			#Range: 0 ~ 100
			diffuserRange = 10

		[elementalcraft.instruments.fireFurnace]
			#The max amount of element consumed by the fire furnace per tick.
			#Range: 0 ~ 1000
			fireFurnaceTransferSpeed = 20
			#The max amount of runes on a fire furnace.
			#Range: 0 ~ 10
			fireFurnaceMaxRunes = 1
			#The amount multiplied by the cooking time of the furnace recipe.
			#Range: 0 ~ 1000
			fireFurnaceElementAmount = 10

			[elementalcraft.instruments.fireFurnace.fireBlastFurnace]
				#The max amount of element consumed by the fire blast furnace per tick.
				#Range: 0 ~ 1000
				fireBlastFurnaceTransferSpeed = 40
				#The max amount of runes on a fire blast furnace.
				#Range: 0 ~ 10
				fireBlastFurnaceMaxRunes = 2
				#The amount multiplied by the cooking time of the blast furnace recipe.
				#Range: 0 ~ 1000
				fireBlastFurnaceElementAmount = 20

		[elementalcraft.instruments.infuser]
			#The max amount of element consumed by the infuser per tick.
			#Range: 0 ~ 1000
			infuserTransferSpeed = 10
			#The max amount of runes on an infuser.
			#Range: 0 ~ 10
			infuserMaxRunes = 1

		[elementalcraft.instruments.binder]
			#The max amount of element consumed by the binder per tick.
			#Range: 0 ~ 1000
			binderTransferSpeed = 25
			#The max amount of runes on an binder.
			#Range: 0 ~ 10
			binderMaxRunes = 2
			#Define if or not binder recip require to be ordered.
			binderRecipeMatchOrder = true

			[elementalcraft.instruments.binder.improved]
				#The max amount of element consumed by the improved binder per tick.
				#Range: 0 ~ 1000
				improvedBinderTransferSpeed = 50
				#The max amount of runes on an improved binder.
				#Range: 0 ~ 10
				improvedBinderMaxRunes = 3

		[elementalcraft.instruments.crystallizer]
			#The max amount of element consumed by the gem crystallizer per tick.
			#Range: 0 ~ 1000
			crystallizerTransferSpeed = 25
			#The max amount of runes on an crystallizer.
			#Range: 0 ~ 10
			crystallizerMaxRunes = 3
			#The ratio of each luck rune on a crystallizer.
			#Range: 0.0 ~ 10.0
			crystallizerLuckRatio = 3.0

		[elementalcraft.instruments.inscriber]
			#The max amount of element consumed by the gem inscriber per tick.
			#Range: 0 ~ 10000
			inscriberTransferSpeed = 1000
			#The max amount of runes on an inscriber.
			#Range: 0 ~ 10
			inscriberMaxRunes = 3

		[elementalcraft.instruments.airMill]
			#The max amount of element consumed by the Air Mill Grindstone per tick.
			#Range: 0 ~ 1000
			airMillTransferSpeed = 10
			#The max amount of runes on an Air Mill Grindstone.
			#Range: 0 ~ 10
			airMillMaxRunes = 3

		[elementalcraft.instruments.purifier]
			#The max amount of element consumed by the Ore Purifier per tick.
			#Range: 0 ~ 1000
			purifierTransferSpeed = 25
			#The max amount of runes on an purifier.
			#Range: 0 ~ 10
			purifierMaxRunes = 3
			#The number of tick for a Ore Purifier to process one item.
			#Range: 0 ~ 2400
			purifierDuration = 100
			#The base cost of a purifier recipe.
			#Range: 0 ~ 10000
			purifierBaseCost = 2500

			[elementalcraft.instruments.purifier.pureOre]
				#Set to false if you want to manually manage processing of pure ore.
				pureOreRecipeInjection = true
				#Set to false if you want pure ore to not use smelting recipes.
				pureOreSmeltingRecipe = true
				#Set to false if you want pure ore to not use blasting recipes.
				pureOreBlastingRecipe = true
				#Set to false if you want pure ore to not use camp fire recipes.
				pureOreCampFireRecipe = true

				[elementalcraft.instruments.purifier.pureOre.ores]
					#The number of input pure ores by a purifier. Using ore blocks.
					#Range: 1 ~ 20
					pureOreOresInput = 1
					#The number of output pure ores by a purifier. Using ore blocks.
					#Range: 1 ~ 20
					pureOreOresOutput = 2
					#The ratio of each luck rune on a purifier.  Using ore blocks.
					#Range: 0.0 ~ 10.0
					pureOreOresLuckRatio = 5.0

				[elementalcraft.instruments.purifier.pureOre.rawMaterials]
					#The number of input pure ores by a purifier. Using raw materials.
					#Range: 1 ~ 20
					pureOreRawMaterialsInput = 3
					#The number of output pure ores by a purifier. Using raw materials.
					#Range: 1 ~ 20
					pureOreRawMaterialsOutput = 4
					#The ratio of each luck rune on a purifier.  Using raw materials.
					#Range: 0.0 ~ 10.0
					pureOreRawMaterialsLuckRatio = 2.0

		[elementalcraft.instruments.elementPipe]
			#The amount of element transferred by impaired pipes.
			#Range: 0 ~ 10000
			impairedPipeTransferAmount = 5
			#The amount of element transferred by pipes.
			#Range: 0 ~ 10000
			pipeTransferAmount = 25
			#The amount of element transferred by improved pipes.
			#Range: 0 ~ 10000
			improvedPipeTransferAmount = 100
			#Cache the last path used by the pipe to increase performances.
			pipePathCache = true

		[elementalcraft.instruments.sorter]
			#The amount of tick between two ordered sorter item transfer.
			#Range: 0 ~ 100
			sorterCooldown = 10
			#The max amount of items an order sorter can filter.
			#Range: 0 ~ 100
			sorterMaxItem = 15

	#Pure Infuser and pedestals config
	[elementalcraft.pureInfuser]
		#The max amount of element consumed by the pure infuser per tick.
		#Range: 0 ~ 1000
		pureInfuserTransferSpeed = 100
		#The max amount of runes on a pure infuser.
		#Range: 0 ~ 10
		pureInfuserMaxRunes = 3

		[elementalcraft.pureInfuser.pedestals]
			#The max amount of runes on a pedestal.
			#Range: 0 ~ 10
			pedestalMaxRunes = 1
			#The element capacity of a pedestal.
			#Range: 0 ~ 100000000
			pedestalCapacity = 10000

	#Items config
	[elementalcraft.items]
		#Define source receptacle durability (0 for unbreakable).
		#Range: 0 ~ 1000
		receptacleDurability = 5
		#Define improved source receptacle durability (0 for unbreakable).
		#Range: 0 ~ 1000
		improvedReceptacleDurability = 20
		#Define if or not receptacles can be enchanted.
		receptacleEnchantable = false
		#The max number of spells on a focus.
		#Range: 1 ~ 20
		focusMaxSpell = 10
		#The max number of spells on an elementalist grimoire.
		#Range: 1 ~ 1000
		spellBookMaxSpell = 100
		#Players start the game with an elementopedia in their inventory.
		playersSpawnWithBook = false
		#The amount of element contained in a single shard.
		#Range: 0 ~ 1000
		shardElementAmount = 250
		#Define chisel durablility (0 for unbreakable).
		#Range: 0 ~ 1000
		chiselDurability = 250

		[elementalcraft.items.elementHolder]
			#The element capacity of an element holder.
			#Range: 0 ~ 100000000
			elementHolderCapacity = 10000
			#The amount of element transferred by an element holder.
			#Range: 0 ~ 1000
			elementHolderTransferAmount = 25

			[elementalcraft.items.elementHolder.pure]
				#The element capacity of a pure element holder.
				#Range: 0 ~ 100000000
				pureElementHolderCapacity = 100000
				#The amount of element transferred by a pure element holder.
				#Range: 0 ~ 1000
				pureElementHolderTransferAmount = 100

	#Spell config
	[elementalcraft.spell]
		#Define if a spell will be cast (and destroyed) or not if you dont have enought element.
		spellConsumeOnFail = false

	#Worldgen config
	[elementalcraft.worldgen]
		#Disable all elementalcraft world gen.
		disableWorldGen = false
		#Disable creation of sources.
		disableSourceSpawn = false
		#Chance to add a source in world (the small the more frequent).
		#Range: 1 ~ 10000
		sourceSpawnChance = 30
		#number of sources at spawn per element type.
		#Range: 1 ~ 20
		sourceSpawnCount = 2
		#Chance to add a source in an ocean biome (the small the more frequent).
		#Range: 1 ~ 10000
		oceanSourceSpawnChance = 150
		#Chance to add a source in world ignoring biome element type (the small the more frequent).
		#Range: 1 ~ 10000
		randomSourceSpawnChance = 300
		#CSource Altar genreration distance setting.
		#Range: 0 ~ 100
		sourceAltarDistance = 64

		[elementalcraft.worldgen.inertCrystal]
			#Disable creation of inertCrystals.
			disableInertCrystal = false
			#Number of inert crystal vein.
			#Range: 1 ~ 100
			inertCrystalCount = 10
			#Size of inert crystal vein.
			#Range: 1 ~ 100
			inertCrystalSize = 9
			#max Y level of inert crystal.
			#Range: 1 ~ 256
			inertCrystalYMax = 96

	#Source config
	[elementalcraft.source]
		#set to true to make sources infinite.
		disableSourceExhaustion = false

	#mod interaction config
	[elementalcraft.interaction]

		[elementalcraft.interaction.botania]
			#Enable interaction with botania.
			botaniaInteracionEnabled = true

			[elementalcraft.interaction.botania.manaSythesizer]
				#The max amount of runes on a Mana Sythesizer.
				#Range: 0 ~ 10
				manaSythesizerMaxRunes = 2
				#The mana capacity of the Mana Sythesizer.
				#Range: 0 ~ 1000000
				manaSythesizerManaCapacity = 10000
				#the multiplier of lense in the Mana Sythesizer (based on 1500)
				#Range: 0 ~ 100
				manaSythesizerLenseElementMultiplier = 50
				#The amount of element 1 mana is worth.
				#Range: 0.0 ~ 100.0
				manaElementRatio = 0.1

		[elementalcraft.interaction.mekanism]
			#Enable interaction with mekanism.
			mekanismInteracionEnabled = true
			#The amount multiplier when using pure ore in mekanism.
			#Range: 0 ~ 20
			mekanismPureOreInputMultiplier = 5
			#The amount multiplier when using pure ore in mekanism.
			#Range: 0 ~ 20
			mekanismPureOreOutputMultiplier = 3
			#Set to false if you want pure ore to not use mekanism dissolution recipes.
			mekanismPureOreDissolutionRecipe = true
			#Set to false if you want pure ore to not use mekanism injecting recipes.
			mekanismPureOreInjectingRecipe = true
			#Set to false if you want pure ore to not use mekanism purifying recipes.
			mekanismPureOrePurifyingRecipe = true
			#Set to false if you want pure ore to not use mekanism enriching recipes.
			mekanismPureOreEnrichingRecipe = true
			#Set to false if you want pure ore to not use mekanism crushing recipes.
			mekanismPureOreCrushingRecipe = true

