
[graphics]

	[graphics.particle]
		#Should particles render on the delayed buffer? This means they will properly render after clouds & water do, but could cause issues with mods like sodium.
		buffer_particles = false

	[graphics.fire]
		#Downwards offset of Minecraft's first-person fire overlay. Higher numbers cause it to visually display lower and free up more screen space.
		#Range: 0.0 ~ 1.0
		fire_overlay_offset = 0.5

[screenshake]
	#Intensity of screenshake. Higher numbers increase amplitude. Disable to turn off screenshake.
	#Range: 0.0 ~ 5.0
	screenshake_intensity = 0.5

[screen_particles]
	#Are screen particles enabled?
	enable_screen_particles = false

